:- module(categories,[]).

category_id(1).
category_id(2).
category_id(3).
category_id(4).
category_id(5).
category_id(6).
category_id(7).
category_id(8).
category_id(9).
category_id(10).
category_id(11).
category_id(12).
category_id(13).
category_id(14).
category_id(15).
category_id(16).
category_id(17).
category_id(18).
category_id(19).
category_id(20).
category_id(21).
category_id(22).
category_id(23).
category_id(24).
category_id(25).
category_id(26).
category_id(27).
category_id(28).
category_id(29).
category_id(30).
category_id(31).
category_id(32).
category_id(33).
category_id(34).
category_id(35).
category_id(36).
category_id(37).
category_id(38).
category_id(39).
category_id(40).
category_id(41).
category_id(42).
category_id(43).
category_id(44).

category_name(1,amusement_park).
category_name(2,animal_camps_and_shows).
category_name(3,archeological).
category_name(4,art_and_craft_centres).
category_name(5,art_galleries).
category_name(6,beaches_and_bay).
category_name(7,caves).
category_name(8,churches).
category_name(9,cinema).
category_name(10,concert_venue).
category_name(11,cultural_show,_cultural_performance).
category_name(12,dam,_reservoir,_lake).
category_name(13,diving_site).
category_name(14,educational_gardens).
category_name(15,educational_museums).
category_name(16,floating_market).
category_name(17,flower_field).
category_name(18,golf_course).
category_name(19,green_travel).
category_name(20,historical_houses).
category_name(21,historical_sites_and_monuments).
category_name(22,hot_spring).
category_name(23,islands).
category_name(24,landmarks_and_memorials).
category_name(25,libraries).
category_name(26,local_market).
category_name(27,meditation).
category_name(28,mosque).
category_name(29,mountain).
category_name(30,museums).
category_name(31,national_parks_and_marine_reserves).
category_name(32,night_market).
category_name(33,outdoor_activity_and_adventure_sites).
category_name(34,parks_and_gardens).
category_name(35,river,_canal).
category_name(36,royal_palace).
category_name(37,sports_venues).
category_name(38,temple).
category_name(39,theater).
category_name(40,training_centers).
category_name(41,village,_community).
category_name(42,waterfalls).
category_name(43,world_war_ii_sites).
category_name(44,zoos_and_aquariums).
