:- use_module(regions,[]).
:- use_module(provinces,[]).
:- use_module(tourist_attractions,[]).
:- use_module(categories,[]).
:- use_module(activities,[]).
:- use_module(seasons,[]).
:- use_module(rules,[]).

thai_paradise :-
  writeln('Welcome to Thai Paradise!'),
  thai_paradise_query('\nPlease select your action:').

thai_paradise_query(Message) :-
  writeln(Message),
  writeln('1: Find tourist attractions based on activity'),
  writeln('2: Find tourist attractions based on opening hours'),
  writeln('3: Find tourist attractions based on age'),
  writeln('4: Find tourist attractions based on cost'),
  writeln('5: Find tourist attractions based on weather'),
  writeln('0: Exit'),
  read(Choice),
  (Choice\=0 ->
    (Choice=1 ->
      writeln('\nPlease select an activity'),
      read(Activity),
      findall([TA,PR,RE,CA,RA],rules:suggest_from_activity(Activity,TA,PR,RE,CA,RA),List),
      length(List,Len),
      random(0,Len,Index),
      nth0(Index,List,[TouristAttraction,Province,Region,Category,Rating]),
      writeln('\nResult found!\n'),
      format('Tourist Attraction: ~w\n',TouristAttraction),
      format('Province: ~w\n',Province),
      format('Region: ~w\n',Region),
      format('Category: ~w\n',Category),
      format('Rating: ~w\n',Rating)
    ; Choice=2 ->
      writeln('\nPlease select from:'),
      writeln('1: Time of day'),
      writeln('2: Opening and closing time'),
      writeln('3: Opening time'),
      writeln('4: Closing time'),
      writeln('5: Currently opened'),
      read(InnerChoice),
      (InnerChoice=1 ->
        writeln('Please select time of day'),
        read(Time),
        findall([TA,PR,RE,CA,RA,OT,CT],rules:suggest_from_opening_hours(Time,TA,PR,RE,CA,RA,OT,CT),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[TouristAttraction,Province,Region,Category,Rating,OpeningTime,ClosingTime]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Opening Time: ~w\n',OpeningTime),
        format('Closing Time: ~w\n',ClosingTime)
      ; InnerChoice=2 ->
        writeln('Please select opening time'),
        read(Opening),
        writeln('Please select closing time'),
        read(Closing),
        findall([TA,PR,RE,CA,RA,OT,CT],rules:suggest_from_opening_and_closing_time(Opening,Closing,TA,PR,RE,CA,RA,OT,CT),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[TouristAttraction,Province,Region,Category,Rating,OpeningTime,ClosingTime]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Opening Time: ~w\n',OpeningTime),
        format('Closing Time: ~w\n',ClosingTime)
      ; InnerChoice=3 ->
        writeln('Please select opening time'),
        read(Opening),
        findall([TA,PR,RE,CA,RA,OT,CT],rules:suggest_from_opening_time(Opening,TA,PR,RE,CA,RA,OT,CT),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[TouristAttraction,Province,Region,Category,Rating,OpeningTime,ClosingTime]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Opening Time: ~w\n',OpeningTime),
        format('Closing Time: ~w\n',ClosingTime)
      ; InnerChoice=4 ->
        writeln('Please select closing time'),
        read(Closing),
        findall([TA,PR,RE,CA,RA,OT,CT],rules:suggest_from_closing_time(Closing,TA,PR,RE,CA,RA,OT,CT),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[TouristAttraction,Province,Region,Category,Rating,OpeningTime,ClosingTime]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Opening Time: ~w\n',OpeningTime),
        format('Closing Time: ~w\n',ClosingTime)
      ; InnerChoice=5 ->
        writeln('Calculating current time'),
        findall([TA,PR,RE,CA,RA,OT,CT],rules:suggest_from_opening_now(TA,PR,RE,CA,RA,OT,CT),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[TouristAttraction,Province,Region,Category,Rating,OpeningTime,ClosingTime]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Opening Time: ~w\n',OpeningTime),
        format('Closing Time: ~w\n',ClosingTime)
      )
    ; Choice=3 ->
      writeln('\nPlease select from:'),
      writeln('1: Age group'),
      writeln('2: Age range'),
      writeln('3: Minimum age'),
      writeln('4: Maximum age'),
      read(InnerChoice),
      (InnerChoice=1 ->
        writeln('Please select age group'),
        read(AgeGroup),
        findall([TA,PR,RE,CA,RA,MIN,MAX],rules:suggest_from_age(AgeGroup,TA,PR,RE,CA,RA,MIN,MAX),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[TouristAttraction,Province,Region,Category,Rating,MinAge,MaxAge]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Minimum Age: ~w\n',MinAge),
        format('Maximum Age: ~w\n',MaxAge)
      ; InnerChoice=2 ->
        writeln('Please select minimum age'),
        read(Min),
        writeln('Please select maximum age'),
        read(Max),
        findall([Min,Max,TA,PR,RE,CA,RA],rules:suggest_from_age(Min,Max,TA,PR,RE,CA,RA),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[MinAge,MaxAge,TouristAttraction,Province,Region,Category,Rating]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Minimum Age: ~w\n',MinAge),
        format('Maximum Age: ~w\n',MaxAge)
      ; InnerChoice=3 ->
        writeln('Please select minimum age'),
        read(Min),
        findall([Min,TA,PR,RE,CA,RA,MAX],rules:suggest_from_min_age(Min,TA,PR,RE,CA,RA,MAX),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[MinAge,TouristAttraction,Province,Region,Category,Rating,MaxAge]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Minimum Age: ~w\n',MinAge),
        format('Maximum Age: ~w\n',MaxAge)
      ; InnerChoice=4 ->
        writeln('Please select maximum age'),
        read(Max),
        findall([Max,TA,PR,RE,CA,RA,MIN],rules:suggest_from_max_age(Max,TA,PR,RE,CA,RA,MIN),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[MaxAge,TouristAttraction,Province,Region,Category,Rating,MinAge]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Minimum Age: ~w\n',MinAge),
        format('Maximum Age: ~w\n',MaxAge)
      )
    ; Choice=4 ->
      writeln('\nPlease select from:'),
      writeln('1: Expensiveness'),
      writeln('2: Cost range'),
      writeln('3: Minimum cost'),
      writeln('4: Maximum cost'),
      read(InnerChoice),
      (InnerChoice=1 ->
        writeln('Please select expensivenes'),
        read(Expensiveness),
        findall([TA,PR,RE,CA,RA,MIN,MAX],rules:suggest_from_cost(Expensiveness,TA,PR,RE,CA,RA,MIN,MAX),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[TouristAttraction,Province,Region,Category,Rating,MinCost,MaxCost]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Minimum Cost: ~w\n',MinCost),
        format('Maximum Cost: ~w\n',MaxCost)
      ; InnerChoice=2 ->
        writeln('Please select minimum cost'),
        read(Min),
        writeln('Please select maximum cost'),
        read(Max),
        findall([Min,Max,TA,PR,RE,CA,RA],rules:suggest_from_cost(Min,Max,TA,PR,RE,CA,RA),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[MinCost,MaxCost,TouristAttraction,Province,Region,Category,Rating]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Minimum Cost: ~w\n',MinCost),
        format('Maximum Cost: ~w\n',MaxCost)
      ; InnerChoice=3 ->
        writeln('Please select minimum cost'),
        read(Min),
        findall([Min,TA,PR,RE,CA,RA,MAX],rules:suggest_from_min_cost(Min,TA,PR,RE,CA,RA,MAX),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[MinCost,TouristAttraction,Province,Region,Category,Rating,MaxCost]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Minimum Cost: ~w\n',MinCost),
        format('Maximum Cost: ~w\n',MaxCost)
      ; InnerChoice=4 ->
        writeln('Please select maximum cost'),
        read(Max),
        findall([Max,TA,PR,RE,CA,RA,MIN],rules:suggest_from_max_cost(Max,TA,PR,RE,CA,RA,MIN),List),
        length(List,Len),
        random(0,Len,Index),
        nth0(Index,List,[MaxCost,TouristAttraction,Province,Region,Category,Rating,MinCost]),
        writeln('\nResult found!\n'),
        format('Tourist Attraction: ~w\n',TouristAttraction),
        format('Province: ~w\n',Province),
        format('Region: ~w\n',Region),
        format('Category: ~w\n',Category),
        format('Rating: ~w\n',Rating),
        format('Minimum Cost: ~w\n',MinCost),
        format('Maximum Cost: ~w\n',MaxCost)
      )
    ; Choice=5 ->
      writeln('Please select weather'),
      read(Weather),
      findall([TA,PR,RE,SE,CA,RA],rules:suggest_from_weather(Weather,TA,PR,RE,SE,CA,RA),List),
      length(List,Len),
      random(0,Len,Index),
      nth0(Index,List,[TouristAttraction,Province,Region,Season,Category,Rating]),
      writeln('\nResult found!\n'),
      format('Tourist Attraction: ~w\n',TouristAttraction),
      format('Province: ~w\n',Province),
      format('Region: ~w\n',Region),
      format('Season: ~w\n',Season),
      format('Category: ~w\n',Category),
      format('Rating: ~w\n',Rating)
    ),
    writeln('\nQuery finished!'),
    thai_paradise_query('\nPlease select your next action:')
  ;
    write('\nThank you for using Thai Paradise!')
  ).
