:- module(provinces,[]).

province_id(1).
province_id(2).
province_id(3).
province_id(4).
province_id(5).
province_id(6).
province_id(7).
province_id(8).
province_id(9).
province_id(10).
province_id(11).
province_id(12).
province_id(13).
province_id(14).
province_id(15).
province_id(16).
province_id(17).
province_id(18).
province_id(19).
province_id(20).
province_id(21).
province_id(22).
province_id(23).
province_id(24).
province_id(25).
province_id(26).
province_id(27).
province_id(28).
province_id(29).
province_id(30).
province_id(31).
province_id(32).
province_id(33).
province_id(34).
province_id(35).
province_id(36).
province_id(37).
province_id(38).
province_id(39).
province_id(40).
province_id(41).
province_id(42).
province_id(43).
province_id(44).
province_id(45).
province_id(46).
province_id(47).
province_id(48).
province_id(49).
province_id(50).
province_id(51).
province_id(52).
province_id(53).
province_id(54).
province_id(55).
province_id(56).
province_id(57).
province_id(58).
province_id(59).
province_id(60).
province_id(61).
province_id(62).
province_id(63).
province_id(64).
province_id(65).
province_id(66).
province_id(67).
province_id(68).
province_id(69).
province_id(70).
province_id(71).
province_id(72).
province_id(73).
province_id(74).
province_id(75).
province_id(76).
province_id(77).

province_name(1,amnat_charoen).
province_name(2,ang_thong).
province_name(3,bangkok).
province_name(4,bueng_kan).
province_name(5,buriram).
province_name(6,chachoengsao).
province_name(7,chai_nat).
province_name(8,chaiyaphum).
province_name(9,chanthaburi).
province_name(10,chiang_mai).
province_name(11,chiang_rai).
province_name(12,chon_buri).
province_name(13,chumphon).
province_name(14,kalasin).
province_name(15,kamphaeng_phet).
province_name(16,kanchanaburi).
province_name(17,khon_kaen).
province_name(18,krabi).
province_name(19,lampang).
province_name(20,lamphun).
province_name(21,loei).
province_name(22,lop_buri).
province_name(23,mae_hong_son).
province_name(24,maha_sarakham).
province_name(25,mukdahan).
province_name(26,nakhon_nayok).
province_name(27,nakhon_pathom).
province_name(28,nakhon_phanom).
province_name(29,nakhon_ratchasima).
province_name(30,nakhon_sawan).
province_name(31,nakhon_si_thammarat).
province_name(32,nan).
province_name(33,narathiwat).
province_name(34,nong_bua_lamphu).
province_name(35,nong_khai).
province_name(36,nonthaburi).
province_name(37,pathum_thani).
province_name(38,pattani).
province_name(39,phang_nga).
province_name(40,phatthalung).
province_name(41,phayao).
province_name(42,phetchabun).
province_name(43,phetchaburi).
province_name(44,phichit).
province_name(45,phitsanulok).
province_name(46,phra_nakhon_si_ayutthaya).
province_name(47,phrae).
province_name(48,phuket).
province_name(49,prachin_buri).
province_name(50,prachuap_khiri_khan).
province_name(51,ranong).
province_name(52,ratchaburi).
province_name(53,rayong).
province_name(54,roi_et).
province_name(55,sa_kaeo).
province_name(56,sakon_nakhon).
province_name(57,samut_prakan).
province_name(58,samut_sakhon).
province_name(59,samut_songkhram).
province_name(60,sara_buri).
province_name(61,satun).
province_name(62,sing_buri).
province_name(63,sisaket).
province_name(64,songkhla).
province_name(65,sukhothai).
province_name(66,suphan_buri).
province_name(67,surat_thani).
province_name(68,surin).
province_name(69,tak).
province_name(70,trang).
province_name(71,trat).
province_name(72,ubon_ratchathani).
province_name(73,udon_thani).
province_name(74,uthai_thani).
province_name(75,uttaradit).
province_name(76,yala).
province_name(77,yasothon).

province_in_region(1,2).
province_in_region(2,3).
province_in_region(3,3).
province_in_region(4,2).
province_in_region(5,2).
province_in_region(6,4).
province_in_region(7,3).
province_in_region(8,2).
province_in_region(9,4).
province_in_region(10,1).
province_in_region(11,1).
province_in_region(12,4).
province_in_region(13,5).
province_in_region(14,2).
province_in_region(15,1).
province_in_region(16,3).
province_in_region(17,2).
province_in_region(18,5).
province_in_region(19,1).
province_in_region(20,1).
province_in_region(21,2).
province_in_region(22,3).
province_in_region(23,1).
province_in_region(24,2).
province_in_region(25,2).
province_in_region(26,3).
province_in_region(27,3).
province_in_region(28,2).
province_in_region(29,2).
province_in_region(30,1).
province_in_region(31,5).
province_in_region(32,1).
province_in_region(33,5).
province_in_region(34,2).
province_in_region(35,2).
province_in_region(36,3).
province_in_region(37,3).
province_in_region(38,5).
province_in_region(39,5).
province_in_region(40,5).
province_in_region(41,1).
province_in_region(42,1).
province_in_region(43,3).
province_in_region(44,1).
province_in_region(45,1).
province_in_region(46,3).
province_in_region(47,1).
province_in_region(48,5).
province_in_region(49,4).
province_in_region(50,3).
province_in_region(51,5).
province_in_region(52,3).
province_in_region(53,4).
province_in_region(54,2).
province_in_region(55,4).
province_in_region(56,2).
province_in_region(57,3).
province_in_region(58,3).
province_in_region(59,3).
province_in_region(60,3).
province_in_region(61,5).
province_in_region(62,3).
province_in_region(63,2).
province_in_region(64,5).
province_in_region(65,1).
province_in_region(66,3).
province_in_region(67,5).
province_in_region(68,2).
province_in_region(69,1).
province_in_region(70,5).
province_in_region(71,4).
province_in_region(72,2).
province_in_region(73,2).
province_in_region(74,1).
province_in_region(75,1).
province_in_region(76,5).
province_in_region(77,2).
