:- module(seasons,[]).

season_id(1).
season_id(2).
season_id(3).
season_id(4).
season_id(5).
season_id(6).
season_id(7).
season_id(8).
season_id(9).
season_id(10).
season_id(11).
season_id(12).
season_id(13).
season_id(14).
season_id(15).

season_name(1,'Winter').
season_name(2,'Summer').
season_name(3,'Rainy').
season_name(4,'Winter').
season_name(5,'Summer').
season_name(6,'Rainy').
season_name(7,'Winter').
season_name(8,'Summer').
season_name(9,'Rainy').
season_name(10,'Winter').
season_name(11,'Summer').
season_name(12,'Rainy').
season_name(13,'Winter').
season_name(14,'Summer').
season_name(15,'Rainy').

season_average_temp(1,17).
season_average_temp(2,28).
season_average_temp(3,23).
season_average_temp(4,20).
season_average_temp(5,29).
season_average_temp(6,24).
season_average_temp(7,22).
season_average_temp(8,34).
season_average_temp(9,26).
season_average_temp(10,21).
season_average_temp(11,32).
season_average_temp(12,28).
season_average_temp(13,22).
season_average_temp(14,33).
season_average_temp(15,26).

season_in_region(1,1).
season_in_region(2,1).
season_in_region(3,1).
season_in_region(4,2).
season_in_region(5,2).
season_in_region(6,2).
season_in_region(7,3).
season_in_region(8,3).
season_in_region(9,3).
season_in_region(10,4).
season_in_region(11,4).
season_in_region(12,4).
season_in_region(13,5).
season_in_region(14,5).
season_in_region(15,5).
